//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
        public string PhoneModel { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
