//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class AppUser {
		public AppUser() {
			this.Tags = new HashSet<Tag>();
		}

		public int ID { get; set; }

		[Display(Name = "First Name")]
		public string FirstName { get; set; }

		[Display(Name = "Surname")]
		public string Surname { get; set; }

		[Display(Name = "Email Address")]
		public string EmailAddress { get; set; }

		[Display(Name = "Phone Number")]
		public string PhoneNumber { get; set; }

		public string PasswordHash { get; set; }

		[Display(Name = "Current Restaurant")]
		public Nullable<int> CurrentRestaurant { get; set; }

		public virtual Restaurant Restaurant { get; set; }
		public virtual ICollection<Tag> Tags { get; set; }
	}
}
