//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserStat
    {
        public int AppUserID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<int> LastRestaurant { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
