//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class AspNetUser {
		public AspNetUser() {
			this.Restaurants = new HashSet<Restaurant>();
		}

		public string Id { get; set; }

		[Display(Name = "User Name")]
		public string UserName { get; set; }

		[Display(Name = "Email Address")]
		public string Email { get; set; }

		[Display(Name = "Phone Number")]
		public string PhoneNumber { get; set; }

		public bool EmailConfirmed { get; set; }
		public string PasswordHash { get; set; }
		public string SecurityStamp { get; set; }
		public bool PhoneNumberConfirmed { get; set; }
		public bool TwoFactorEnabled { get; set; }
		public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
		public bool LockoutEnabled { get; set; }
		public int AccessFailedCount { get; set; }

		public virtual ICollection<Restaurant> Restaurants { get; set; }
	}
}
