//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Patron {
		public Patron() {
			this.Tags = new HashSet<Tag>();
		}

		public int ID { get; set; }

		[Required]
		[Display(Name = "First Name")]
		[StringLength(50, MinimumLength = 3, ErrorMessage = "{0} must be between {2} and {1} characters long.")]
		public string FirstName { get; set; }

		[Required]
		[Display(Name = "Surname")]
		[StringLength(50, MinimumLength = 3, ErrorMessage = "{0} must be between {2} and {1} characters long.")]
		public string Surname { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		[StringLength(50, MinimumLength = 6, ErrorMessage = "{0} must be between {2} and {1} characters long.")]
		public string PasswordHash { get; set; }

		[Required]
		[DataType(DataType.EmailAddress)]
		[Display(Name = "Email Address")]
		public string EmailAddress { get; set; }

		public virtual ICollection<Tag> Tags { get; set; }
	}
}
