//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Restaurant {
		public Restaurant() {
			this.AppUsers = new HashSet<AppUser>();
			this.Tags = new HashSet<Tag>();
		}

		public int ID { get; set; }

		[Display(Name = "Name")]
		public string Name { get; set; }

		[Display(Name = "Map")]
		public byte[] Map { get; set; }

		[Display(Name = "Administrator")]
		public string Admin { get; set; }

		[Display(Name = "Custom Label")]
		public virtual AspNetUser AspNetUser { get; set; }

		public virtual ICollection<AppUser> AppUsers { get; set; }
		public virtual ICollection<Tag> Tags { get; set; }
	}
}
