//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.ComponentModel.DataAnnotations;

	public partial class Tag {
		public int ID { get; set; }

		[Display(Name = "Custom Label")]
		public string Label { get; set; }

		[Display(Name = "Owning Restaurant")]
		public Nullable<int> Restaurant { get; set; }

		[Display(Name = "Current App User")]
		public Nullable<int> CurrentUser { get; set; }

		[Display(Name = "Current App User")]
		public virtual AppUser AppUser { get; set; }

		[Display(Name = "Owning Restaurant")]
		public virtual Restaurant Restaurant1 { get; set; }
	}
}
