//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models {
	using System;
	using System.ComponentModel.DataAnnotations;

	public partial class Tag {
		public int ID { get; set; }

		[Display(Name = "Linked Patron")]
		public Nullable<int> CurrentPatron { get; set; }

		[Display(Name = "Custom Label")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "{0} must be between {2} and {1} characters long.")]
		public string Label { get; set; }

		public virtual Patron Patron { get; set; }
	}
}
