//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.Transmitters = new HashSet<Transmitter>();
        }
    
        public int ID { get; set; }
        public string ZoneName { get; set; }
        public int Restaurant { get; set; }
    
        public virtual Restaurant RestaurantZ { get; set; }
        public virtual ICollection<Transmitter> Transmitters { get; set; }
    }
}
