#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KinderFinder.Resource", IsApplication=true)]

namespace KinderFinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int Main_Email = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Main_Login = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Main_Password = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int Main_ProgressBar = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Main_Register = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int Main_Remember = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int Register_Email = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Register_FirstName = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int Register_Password = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Register_PasswordConfirm = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int Register_Phone = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int Register_ProgressBar = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int Register_Register = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int Register_Surname = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int RestList_List = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int TagList_List = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int TagList_Track = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int TagList_Warning = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int Track_DownloadingText = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int Track_Map = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int Track_ProgressBar = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RestaurantList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TagList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TrackTags = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
