#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KinderFinder.Resource", IsApplication=true)]

namespace KinderFinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001e
			public const int MainMenu = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int Main_Email = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int Main_Login = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int Main_Password = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int Main_ProgressBar = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int Main_Register = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Main_Remember = 2131034115;
			
			// aapt resource value: 0x7f050020
			public const int Menu_Exit = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int Menu_LogOut = 2131034143;
			
			// aapt resource value: 0x7f05000a
			public const int Register_Email = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int Register_FirstName = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int Register_Password = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Register_PasswordConfirm = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int Register_Phone = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int Register_ProgressBar = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int Register_Register = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int Register_Surname = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int RestList_Clear = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int RestList_List = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int RestList_Search = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int TagConfig_Cancel = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int TagConfig_Colour = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int TagConfig_Name = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int TagConfig_Save = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int TagList_List = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int TagList_Track = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int TagList_Warning = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int Track_DownloadingText = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int Track_Map = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int Track_ProgressBar = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout2 = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RestaurantList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TagConfig = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TagList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TrackTags = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f040000
			public const int MainMenu = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
	}
}
#pragma warning restore 1591
